### ISSUE TITLE
127.0.0.1_route 启动失败

### ISSUE THREAD

**Issue by Tes99t01** [FISCO-BCOS/meshchain#4]
搭建meshchain过程中都无异常，解压路由rout后执行启动脚本报如下错误：
sh start_meshchain.sh 

sed：无法读取 ./systemcontractv2/config.js：没有那个文件或目录
module.js:549

Error: Cannot find module '../web3lib/config'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
...
deploy system contract failed

经查看./systemcontractv2/config.js文件的确不存在，如何才能正常执行sh start_meshchain.sh ？非常谢谢！

**Comment by iamyh** [comment]
这个报错是由于版本迭代，文件存放的位置变更导致的。将会在四月份的版本解决。

感谢
